# @package _global_
simulator:
  sim:
    dt: 0.004
    substeps: 1
    gravity: [0.0, 0.0, -9.81]
    up_axis: 1
    physx:
      num_threads: 10
      solver_type: 1
      num_position_iterations: 4
      num_velocity_iterations: 2
      contact_offset: 0.01
      rest_offset: 0.0
      bounce_threshold_velocity: 0.5
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608
      default_buffer_size_multiplier: 5
      contact_collection: 2