# @package _global_
defaults:
  - /simulator/base
  - /terrain/plane

task:
  name: g1_im
  seed: 0
  env:
    num_envs: 8192
    env_spacing: 5.0  # not used with heightfields/trimeshes
    max_episode_length_sec: 20 # max episode length in seconds
    
    motion_dt: 0.05  # sec
    motion_horizon: 10

  init_state:
    pos: [0.0, 0.0, 0.15] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: {
      # upper body joints
      "left_shoulder_roll_joint": 0.35, 
      "left_elbow_joint": 0.78,
      "right_shoulder_roll_joint": -0.35,
      "right_elbow_joint": 0.78,
      
      # lower body joints
      "left_hip_pitch_joint": -0.3,
      "left_knee_joint": 0.6,
      "left_ankle_pitch_joint": -0.3,
      "right_hip_pitch_joint": -0.3,
      "right_knee_joint": 0.6,
      "right_ankle_pitch_joint": -0.3,
        }

  # dataset for tracking reference
  tracking_reference:
    prefix: "./resources/dataset/g1_29dof_data"
    folder: "full_train"
    joint_mapping: "joint_id.txt"    
    # resample motion (for universal tracking)
    resample_motion: True

    randomize_motion_speed: True
    motion_speed_range: [0.75, 1.25]

    motion_filter:
      min_time: 2.0 # sec
      link_height_offset: -0.075 # m
      floor_height_offset: 0.05 # m
      base_height_range: [0.2, 1.5] # m
      base_roll_range: None # rad
      base_pitch_range: None # rad

  # dataset for skill imitation
  skill_demonstration:
    prefix: "./resources/dataset/g1_29dof_data"
    folder: "run_train"
    joint_mapping: "joint_id.txt"

  observation:
    clip_observations: 100
    
    obs_scales:
      rotation: 1.0
      base_pos: 1.0
      body_pos: 1.0
      base_lin_vel: 2.0
      base_ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05
      gravity: 1.0
      height_points: 5.0 
    
    add_noise: True
    noise_scales:
      rotation: 0.05
      base_pos: 0.05
      body_pos: 0.02
      base_lin_vel: 0.1
      base_ang_vel: 0.2
      dof_pos: 0.01
      dof_vel: 0.5
      gravity: 0.05
      height_points: 0.1

  domain_rand:
    randomize_base_payload: True
    added_payload_range: [-0.1, 0.2]

    randomize_link_mass: True
    link_mass_range: [0.8, 1.2]

    randomize_link_com: True
    link_com_range: [-0.1, 0.1]

    randomize_restitution: True
    restitution_range: [0.0, 0.1]

    randomize_friction: True
    friction_range: [0.5, 1.5]

    randomize_joint_friction: True
    joint_friction_range: [0.2, 1.5]

    randomize_joint_damping: True
    joint_damping_range: [0.3, 1.5]

    randomize_joint_armature: True
    joint_armature_range: [0.001, 0.025]

    randomize_pd_gain: True
    kp_range: [0.8, 1.2]
    kd_range: [0.8, 1.2]

    randomize_joint_injection: True
    joint_injection_range: [-0.01, 0.01]

    randomize_actuation_offset: True
    actuation_offset_range: [-0.01, 0.01]

    randomize_initial_joint_position: True
    initial_joint_offset_range: [-0.01, 0.01]

    push_robot_base: True
    push_robot_base_interval_sec: [5.0, 8.0] # sec
    push_robot_base_max_lin_vel: 0.25 # m/s

    push_robot_body: True
    push_robot_body_interval_sec: [5.0, 8.0] # sec
    push_robot_body_duration_sec: [0.5, 1.0] # sec
    push_robot_body_max_force: 20 # N
    push_robot_body_max_torque: 20 # N * m

  rewards:
    scales:
      tracking_trunk_lin_vel: 4.0
      tracking_trunk_ang_vel: 4.0
      tracking_trunk_vel_dir: 4.0
      
      tracking_joint_pos: 8.0
      tracking_marker_pos: 4.0
      tracking_feet_height: 4.0
      tracking_keyframe_height: 2.0
      
      penalty_torques: -1.0
      penalty_action_rates: -7.0
      penalty_action_smoothness: -2.0
      
      feet_stumble: -10.0
      feet_slippage: -1.5
      feet_distance: -10.0
      feet_air_time: -10.0
      
      alive: 7.0
      deviation: -10.0
      termination: -10.0
      
      dof_pos_limits: -10.0
      dof_vel_limits: -10.0
      torque_limits: -5.0
      action_limits: -5.0
        
    only_positive_rewards: False
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torques_limit: 0.9
    
    feet_height_target: 0.05 # m
    feet_xy_dist_target: 0.1 # m
    feet_air_time_target: 0.25 # sec
    
    momentum: 0.005
    init_sigma: 100.0
    init_coefficient: 100.0
    
  termination:
    termination_height: 0.5 # m
    deviation_distance: 0.25 # m
          
  # viewer camera:
  viewer:
    ref_env: 0
    pos: [5.0, -5.0, 3.0]  # [m]
    lookat: [5.0, -2.0, 2.0]  # [m]