# @package _global_

robot:
  control:
        clip_action: 100.0
        control_type: "M" # P: position, V: velocity, T: torques
        # PD Drive parameters:
        stiffness: {"hip": 100, "knee": 200, "ankle": 40, "waist": 300, "shoulder": 50, "elbow": 50, "wrist": 20} # [N*m/rad]
        damping: {"hip": 2, "knee": 4, "ankle": 2, "waist": 5, "shoulder": 2, "elbow": 1, "wrist": 0.5}  # [N*m*s/rad]
        rapid_action_names: ["ankle", "shoulder", "elbow"]
        sluggish_action_names: ["hip", "knee", "waist"]
        action_scale: 0.25
        # decimation: Number of control action updates @ sim DT per policy DT
        decimation: 5
  asset:
        file: "./resources/robots/G1/urdf/g1_29dof.urdf"
        name: "g1_29dof"  # actor name
        
        # joint setting
        upper_dof_names: ["shoulder", "elbow"]
        lower_dof_names: ["waist", "hip", "knee"]
        
        # body & keyframe setting
        keyframe_name: "keyframe"
        feet_contact_binding: {"left_ankle": "left_ankle_roll_link", "right_ankle": "right_ankle_roll_link",}
        trunk_names : ["pelvis", ["torso", "head"]]  # navigation
        mobile_names: ["pelvis", ["knee", "ankle"]]  # locomotion
        marker_names: ["torso",  ["wrist"]]  # manipulation
        endeffector_names: ["pelvis", ["torso", "ankle", "elbow", "wrist"]]
        
        payload_name: "torso_link"
        perturb_body_names: ["torso_link", "ankle_roll_link", 
                              "wrist_roll_rubber_hand", "wrist_yaw_link"]
        terminate_after_contacts_on: []
        penalised_contacts_on: ["torso_link", "hip", "elbow", "shoulder"]
        
        # Merge bodies connected by fixed joints.
        # Specific fixed joints can be kept by adding " <... dont_collapse="true">
        collapse_fixed_joints: True
        disable_gravity: False
        fix_base_link: False # fixe the base of the robot
        default_dof_drive_mode: 3 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
        self_collisions: 0 # 1 to disable, 0 to enable...bitwise filter
        replace_cylinder_with_capsule: True # replace collision cylinders with capsules, leads to faster/more stable simulation
        flip_visual_attachments: False # Some .obj meshes must be flipped from y-up to z-up
        
        density: 0.001
        angular_damping: 0.0
        linear_damping: 0.0
        max_angular_velocity: 1000.0
        max_linear_velocity: 1000.0
        armature: 0.0
        thickness: 0.01