# @package _global_

defaults:
  - base

terrain:
  terrain:
    mesh_type: plane
    horizontal_scale: 0.1
    vertical_scale: 0.005
    border_size: 25
    curriculum: true
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0
    measure_heights: true
    measured_points_x: [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
    measured_points_y: [-0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
    selected: false
    terrain_kwargs: null
    max_init_terrain_level: 0
    terrain_length: 8.0
    terrain_width: 8.0
    num_rows: 10
    num_cols: 20
    terrain_proportions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
    slope_treshold: 0.75
    hard_terrain: true
    max_terrain_level: 9